server:
  port: 9001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://117.72.67.117:3306/school-coupon?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: Lxh1134153700
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
  #消息队列
  rabbitmq:
    host: 117.72.67.117
    port: 5672
    username: lxh
    password: Lxh1134153700
    virtual-host: /
    #手动开启确认消息
    listener:
      simple:
        acknowledge-mode: manual



  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 117.72.67.117
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Lxh1134153700
    # 连接超时时间
    timeout: 2s
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  #nacos
  cloud:
    nacos:
      server-addr: 117.72.67.117:8848
      discovery:
        username: lxh
        password: Lxh1134153700
        namespace: dev
  application:
    name: school-coupon-service

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



#自定义消息队列配置，发送锁定库存消息-》延迟exchange-》lock.queue-》死信exchange-》release.queue
mqconfig:
  #延迟队列，不能被监听消费
  coupon_release_delay_queue: coupon.release.delay.queue
  #延迟队列的消息过期后转发的队列
  coupon_release_queue: coupon.release.queue
  #交换机
  coupon_event_exchange: coupon.event.exchange
  #进入延迟队列的路由key
  coupon_release_delay_routing_key: coupon.release.delay.routing.key
  #消息过期，进入释放死信队列的key
  coupon_release_routing_key: coupon.release.routing.key
  #消息过期时间,毫秒,测试改为15秒
  ttl: 15000
