server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://117.72.67.117:3306/school-auth?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: Lxh1134153700
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true

  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 117.72.67.117
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Lxh1134153700
    # 连接超时时间
    timeout: 2s
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0


  #邮箱服务配置
  mail:
    host: smtp.163.com #发送邮件服务器
    username: 13695975690@163.com #发送邮件的邮箱地址
    password: WXRZOWQMXTSNARWR #客户端授权码，不是邮箱密码,网易的是自己设置的
    from: 13695975690@163.com # 发送邮件的地址，和上面username一致

    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
